apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
  labels:
    pv: nfs-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /data/nfs
    server: 192.168.26.247
